spring:
  config:
    activate:
      on-profile:
        - dev
currency:
  service:
    uri: http://localhost/v1/api/office/
user:
  service:
    registration:
      http://localhost:81/api/v1/users/registration
    about:
      http://localhost:81/api/v1/users/me/
    update:
      http://localhost:81/api/v1/users/update/
admin:
  user:
    count: http://localhost:81/v1/api/administration/user/count