spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: POSTGRESQL

  datasource:
    username: postgres
    password: 172143
    url: jdbc:postgresql://db:5432/finance-service?currentSchema=finance
    driver-class-name: org.postgresql.Driver
server:
  port: 80