currency:
  service:
    uri: http://finance-service/v1/api/office/
user:
  service:
    registration:
      http://user-service/api/v1/users/registration
    about:
      http://user-service/api/v1/users/me/
    update:
      http://user-service/api/v1/users/update/